% Q1.4

disp('San Diego')
n = 359;
delta = 23.45 * sind(360*(284+n)/365);
omega = -1.5*15;
lat = 33;
zenSD = acosd(cosd(lat)*cosd(delta)*cosd(omega)+sind(lat)*sind(delta));
betaa = 0;
betab = 30;
betac = 45;
azib = 180;
azic = 150;

incia = acosd(sind(delta)*sind(lat)*cosd(betaa)-...
    sind(delta)*cosd(lat)*sind(betaa)*cosd(azib)+...
    cosd(delta)*cosd(lat)*cosd(betaa)*cosd(omega)+...
    cosd(delta)*sind(lat)*sind(betaa)*cosd(azib)*cosd(omega)+...
    cosd(delta)*sind(betaa)*sind(azib)*sind(omega));

incib = acosd(sind(delta)*sind(lat)*cosd(betab)-...
    sind(delta)*cosd(lat)*sind(betab)*cosd(azib)+...
    cosd(delta)*cosd(lat)*cosd(betab)*cosd(omega)+...
    cosd(delta)*sind(lat)*sind(betab)*cosd(azib)*cosd(omega)+...
    cosd(delta)*sind(betab)*sind(azib)*sind(omega));

incic = acosd(sind(delta)*sind(lat)*cosd(betac)-...
    sind(delta)*cosd(lat)*sind(betac)*cosd(azib)+...
    cosd(delta)*cosd(lat)*cosd(betac)*cosd(omega)+...
    cosd(delta)*sind(lat)*sind(betac)*cosd(azib)*cosd(omega)+...
    cosd(delta)*sind(betac)*sind(azib)*sind(omega));

disp(incia)
disp(incib)
disp(incic)


disp('Melbourne')
n = 359;
delta = 23.45 * sind(360*(284+n)/365);
omega = -1.5*15;
lat = 37;
zenSD = acosd(cosd(lat)*cosd(delta)*cosd(omega)+sind(lat)*sind(delta));
betaa = 0;
betab = 30;
betac = 45;
azib = 180;
azic = 150;

incia = acosd(sind(delta)*sind(lat)*cosd(betaa)-...
    sind(delta)*cosd(lat)*sind(betaa)*cosd(azib)+...
    cosd(delta)*cosd(lat)*cosd(betaa)*cosd(omega)+...
    cosd(delta)*sind(lat)*sind(betaa)*cosd(azib)*cosd(omega)+...
    cosd(delta)*sind(betaa)*sind(azib)*sind(omega));

incib = acosd(sind(delta)*sind(lat)*cosd(betab)-...
    sind(delta)*cosd(lat)*sind(betab)*cosd(azib)+...
    cosd(delta)*cosd(lat)*cosd(betab)*cosd(omega)+...
    cosd(delta)*sind(lat)*sind(betab)*cosd(azib)*cosd(omega)+...
    cosd(delta)*sind(betab)*sind(azib)*sind(omega));

incic = acosd(sind(delta)*sind(lat)*cosd(betac)-...
    sind(delta)*cosd(lat)*sind(betac)*cosd(azib)+...
    cosd(delta)*cosd(lat)*cosd(betac)*cosd(omega)+...
    cosd(delta)*sind(lat)*sind(betac)*cosd(azib)*cosd(omega)+...
    cosd(delta)*sind(betac)*sind(azib)*sind(omega));

disp(incia)
disp(incib)
disp(incic)